name: COBOL Check Automation
on:
  push:
    branches: [ main ]
jobs:
  cobol-check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'
    - name: Install Zowe CLI
      run: npm install -g @zowe/cli
    - name: Install Zowe plugins
      run: |
        zowe plugins install @zowe/cli-zos-files-for-zowe-cli
        zowe plugins install @zowe/cli-zos-jobs-for-zowe-cli
        zowe plugins install @zowe/cli-cics-for-zowe-cli
        zowe plugins install @zowe/cli-ims-for-zowe-cli
      
    - name: Setup Mainframe Environment and Upload COBOL Check
      env:
        ZOWE_USERNAME: ${{ secrets.ZOWE_USERNAME }}
        ZOWE_PASSWORD: ${{ secrets.ZOWE_PASSWORD }}
      run: |
        echo "ZOWE_USERNAME is: $ZOWE_USERNAME"
        chmod +x .github/scripts/zowe_operations.sh
        .github/scripts/zowe_operations.sh
